
FROM node:18 AS build
WORKDIR /app

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

ARG VITE_WS_URL
ENV VITE_WS_URL = $VITE_WS_URL


COPY ./Frontend/package*.json .
RUN npm install


COPY ./Frontend .
RUN npm run build


FROM nginx:alpine


COPY ./Nginx/nginx-prod.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

# Expose port
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
